name: Output Information
on: workflow_dispatch
jobs:
    info:
        runs-on: ubuntu-latest
        steps:
            - name: Output GitHub context
              run: echo "${{ toJSON(github) }}" # expression. "github" is a reserved key that has context info.
